import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./Providers";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, criteria }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-3xl mx-auto p-4">
        {
          criteria ? 
            <Navbar /> : null
          
        }
        <div className="mt-8">
          <AuthProvider>
            {children}
          </AuthProvider>
        
        </div>
        </div>
        </body>
        
    </html>
  );
}
